FROM golang:1.25-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o drift-guard-api ./cmd/playground

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /app/drift-guard-api .

EXPOSE 8080
ENV PORT=8080
CMD ["./drift-guard-api"]
