// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: api/drift-agent/v1/drift-agent.proto

package driftagentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DiffEngine_Diff_FullMethodName = "/drift_agent.v1.DiffEngine/Diff"
)

// DiffEngineClient is the client API for DiffEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DiffEngine compares two API schema files and returns a classified diff.
type DiffEngineClient interface {
	Diff(ctx context.Context, in *DiffRequest, opts ...grpc.CallOption) (*DiffResponse, error)
}

type diffEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewDiffEngineClient(cc grpc.ClientConnInterface) DiffEngineClient {
	return &diffEngineClient{cc}
}

func (c *diffEngineClient) Diff(ctx context.Context, in *DiffRequest, opts ...grpc.CallOption) (*DiffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiffResponse)
	err := c.cc.Invoke(ctx, DiffEngine_Diff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiffEngineServer is the server API for DiffEngine service.
// All implementations must embed UnimplementedDiffEngineServer
// for forward compatibility.
//
// DiffEngine compares two API schema files and returns a classified diff.
type DiffEngineServer interface {
	Diff(context.Context, *DiffRequest) (*DiffResponse, error)
	mustEmbedUnimplementedDiffEngineServer()
}

// UnimplementedDiffEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiffEngineServer struct{}

func (UnimplementedDiffEngineServer) Diff(context.Context, *DiffRequest) (*DiffResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Diff not implemented")
}
func (UnimplementedDiffEngineServer) mustEmbedUnimplementedDiffEngineServer() {}
func (UnimplementedDiffEngineServer) testEmbeddedByValue()                    {}

// UnsafeDiffEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiffEngineServer will
// result in compilation errors.
type UnsafeDiffEngineServer interface {
	mustEmbedUnimplementedDiffEngineServer()
}

func RegisterDiffEngineServer(s grpc.ServiceRegistrar, srv DiffEngineServer) {
	// If the following call panics, it indicates UnimplementedDiffEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiffEngine_ServiceDesc, srv)
}

func _DiffEngine_Diff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiffEngineServer).Diff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiffEngine_Diff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiffEngineServer).Diff(ctx, req.(*DiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiffEngine_ServiceDesc is the grpc.ServiceDesc for DiffEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiffEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "drift_agent.v1.DiffEngine",
	HandlerType: (*DiffEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Diff",
			Handler:    _DiffEngine_Diff_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/drift-agent/v1/drift-agent.proto",
}
