// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/drift-guard/v1/drift-guard.proto

package driftguardv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiffRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw content of the base schema file.
	BaseContent []byte `protobuf:"bytes,1,opt,name=base_content,json=baseContent,proto3" json:"base_content,omitempty"`
	// Raw content of the head schema file.
	HeadContent []byte `protobuf:"bytes,2,opt,name=head_content,json=headContent,proto3" json:"head_content,omitempty"`
	// Original filename of the base file (used for extension-based type detection).
	BaseName string `protobuf:"bytes,3,opt,name=base_name,json=baseName,proto3" json:"base_name,omitempty"`
	// Original filename of the head file.
	HeadName string `protobuf:"bytes,4,opt,name=head_name,json=headName,proto3" json:"head_name,omitempty"`
	// Explicit schema type: "openapi", "graphql", or "grpc".
	// If omitted, auto-detected from base_name extension.
	Type          string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffRequest) Reset() {
	*x = DiffRequest{}
	mi := &file_api_drift_guard_v1_drift_guard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffRequest) ProtoMessage() {}

func (x *DiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_drift_guard_v1_drift_guard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffRequest.ProtoReflect.Descriptor instead.
func (*DiffRequest) Descriptor() ([]byte, []int) {
	return file_api_drift_guard_v1_drift_guard_proto_rawDescGZIP(), []int{0}
}

func (x *DiffRequest) GetBaseContent() []byte {
	if x != nil {
		return x.BaseContent
	}
	return nil
}

func (x *DiffRequest) GetHeadContent() []byte {
	if x != nil {
		return x.HeadContent
	}
	return nil
}

func (x *DiffRequest) GetBaseName() string {
	if x != nil {
		return x.BaseName
	}
	return ""
}

func (x *DiffRequest) GetHeadName() string {
	if x != nil {
		return x.HeadName
	}
	return ""
}

func (x *DiffRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type DiffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changes       []*Change              `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	Summary       *Summary               `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffResponse) Reset() {
	*x = DiffResponse{}
	mi := &file_api_drift_guard_v1_drift_guard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffResponse) ProtoMessage() {}

func (x *DiffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_drift_guard_v1_drift_guard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffResponse.ProtoReflect.Descriptor instead.
func (*DiffResponse) Descriptor() ([]byte, []int) {
	return file_api_drift_guard_v1_drift_guard_proto_rawDescGZIP(), []int{1}
}

func (x *DiffResponse) GetChanges() []*Change {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *DiffResponse) GetSummary() *Summary {
	if x != nil {
		return x.Summary
	}
	return nil
}

type Change struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Before        string                 `protobuf:"bytes,7,opt,name=before,proto3" json:"before,omitempty"`
	After         string                 `protobuf:"bytes,8,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Change) Reset() {
	*x = Change{}
	mi := &file_api_drift_guard_v1_drift_guard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change) ProtoMessage() {}

func (x *Change) ProtoReflect() protoreflect.Message {
	mi := &file_api_drift_guard_v1_drift_guard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change.ProtoReflect.Descriptor instead.
func (*Change) Descriptor() ([]byte, []int) {
	return file_api_drift_guard_v1_drift_guard_proto_rawDescGZIP(), []int{2}
}

func (x *Change) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Change) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Change) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Change) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Change) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Change) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Change) GetBefore() string {
	if x != nil {
		return x.Before
	}
	return ""
}

func (x *Change) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

type Summary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Breaking      int32                  `protobuf:"varint,2,opt,name=breaking,proto3" json:"breaking,omitempty"`
	NonBreaking   int32                  `protobuf:"varint,3,opt,name=non_breaking,json=nonBreaking,proto3" json:"non_breaking,omitempty"`
	Info          int32                  `protobuf:"varint,4,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Summary) Reset() {
	*x = Summary{}
	mi := &file_api_drift_guard_v1_drift_guard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Summary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Summary) ProtoMessage() {}

func (x *Summary) ProtoReflect() protoreflect.Message {
	mi := &file_api_drift_guard_v1_drift_guard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Summary.ProtoReflect.Descriptor instead.
func (*Summary) Descriptor() ([]byte, []int) {
	return file_api_drift_guard_v1_drift_guard_proto_rawDescGZIP(), []int{3}
}

func (x *Summary) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Summary) GetBreaking() int32 {
	if x != nil {
		return x.Breaking
	}
	return 0
}

func (x *Summary) GetNonBreaking() int32 {
	if x != nil {
		return x.NonBreaking
	}
	return 0
}

func (x *Summary) GetInfo() int32 {
	if x != nil {
		return x.Info
	}
	return 0
}

var File_api_drift_guard_v1_drift_guard_proto protoreflect.FileDescriptor

const file_api_drift_guard_v1_drift_guard_proto_rawDesc = "" +
	"\n" +
	"$api/drift-guard/v1/drift-guard.proto\x12\x0edrift_guard.v1\"\xa1\x01\n" +
	"\vDiffRequest\x12!\n" +
	"\fbase_content\x18\x01 \x01(\fR\vbaseContent\x12!\n" +
	"\fhead_content\x18\x02 \x01(\fR\vheadContent\x12\x1b\n" +
	"\tbase_name\x18\x03 \x01(\tR\bbaseName\x12\x1b\n" +
	"\thead_name\x18\x04 \x01(\tR\bheadName\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\"s\n" +
	"\fDiffResponse\x120\n" +
	"\achanges\x18\x01 \x03(\v2\x16.drift_guard.v1.ChangeR\achanges\x121\n" +
	"\asummary\x18\x02 \x01(\v2\x17.drift_guard.v1.SummaryR\asummary\"\xd0\x01\n" +
	"\x06Change\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x16\n" +
	"\x06before\x18\a \x01(\tR\x06before\x12\x14\n" +
	"\x05after\x18\b \x01(\tR\x05after\"r\n" +
	"\aSummary\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x1a\n" +
	"\bbreaking\x18\x02 \x01(\x05R\bbreaking\x12!\n" +
	"\fnon_breaking\x18\x03 \x01(\x05R\vnonBreaking\x12\x12\n" +
	"\x04info\x18\x04 \x01(\x05R\x04info2O\n" +
	"\n" +
	"DiffEngine\x12A\n" +
	"\x04Diff\x12\x1b.drift_guard.v1.DiffRequest\x1a\x1c.drift_guard.v1.DiffResponseBHZFgithub.com/pgomes13/api-drift-engine/api/drift-guard/v1;driftguardv1b\x06proto3"

var (
	file_api_drift_guard_v1_drift_guard_proto_rawDescOnce sync.Once
	file_api_drift_guard_v1_drift_guard_proto_rawDescData []byte
)

func file_api_drift_guard_v1_drift_guard_proto_rawDescGZIP() []byte {
	file_api_drift_guard_v1_drift_guard_proto_rawDescOnce.Do(func() {
		file_api_drift_guard_v1_drift_guard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_drift_guard_v1_drift_guard_proto_rawDesc), len(file_api_drift_guard_v1_drift_guard_proto_rawDesc)))
	})
	return file_api_drift_guard_v1_drift_guard_proto_rawDescData
}

var file_api_drift_guard_v1_drift_guard_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_drift_guard_v1_drift_guard_proto_goTypes = []any{
	(*DiffRequest)(nil),  // 0: drift_guard.v1.DiffRequest
	(*DiffResponse)(nil), // 1: drift_guard.v1.DiffResponse
	(*Change)(nil),       // 2: drift_guard.v1.Change
	(*Summary)(nil),      // 3: drift_guard.v1.Summary
}
var file_api_drift_guard_v1_drift_guard_proto_depIdxs = []int32{
	2, // 0: drift_guard.v1.DiffResponse.changes:type_name -> drift_guard.v1.Change
	3, // 1: drift_guard.v1.DiffResponse.summary:type_name -> drift_guard.v1.Summary
	0, // 2: drift_guard.v1.DiffEngine.Diff:input_type -> drift_guard.v1.DiffRequest
	1, // 3: drift_guard.v1.DiffEngine.Diff:output_type -> drift_guard.v1.DiffResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_drift_guard_v1_drift_guard_proto_init() }
func file_api_drift_guard_v1_drift_guard_proto_init() {
	if File_api_drift_guard_v1_drift_guard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_drift_guard_v1_drift_guard_proto_rawDesc), len(file_api_drift_guard_v1_drift_guard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_drift_guard_v1_drift_guard_proto_goTypes,
		DependencyIndexes: file_api_drift_guard_v1_drift_guard_proto_depIdxs,
		MessageInfos:      file_api_drift_guard_v1_drift_guard_proto_msgTypes,
	}.Build()
	File_api_drift_guard_v1_drift_guard_proto = out.File
	file_api_drift_guard_v1_drift_guard_proto_goTypes = nil
	file_api_drift_guard_v1_drift_guard_proto_depIdxs = nil
}
